spring:
  application:
    name: EurekaServer  #应用名称
server:
  port: 8761  #内置的tomcat服务启动监听端口号

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #此EurekaServer不在注册到其他的注册中心
    fetch-registry: false       #不在从其他中心中心拉取服务器信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka